[development]
address = "localhost"
template_dir = "www/templates"
port = 9080
workers = 1
keep_alive = 5
log = "normal"
secret_key = "ot023skcNuA7UAnQonI72Nhmyrbzoapeu59e8877m0A="
limits = { forms = 32768 }

[production]
address = "localhost" # [<-- SERVER IP ADDRESS HERE]
template_dir = "www/templates"
port = 80
workers = 1
keep_alive = 5
log = "normal"
#secret_key = [randomly generated at launch] or use "openssl rand -base64 32" to generate one
limits = { forms = 32768 }